export default function Main() {
  return (
    <>
      <div>MAIN</div>
      <div>MAIN</div>
      <div>MAIN</div>
      <div>MAIN</div>
      <div>MAIN</div>
      <div>MAIN</div>
      <div>MAIN</div>
      <div>MAIN</div>
      <div>MAIN</div>
      <div>MAIN</div>
      <div>MAIN</div>
      <div>MAIN</div>
      <div>MAIN</div>
      <div>MAIN</div>
      <div>MAIN</div>
      <div>MAIN</div>
      <div>MAIN</div>
      <div>MAIN</div>
      <div>MAIN</div>
      <div>MAIN</div>
      <div>MAIN</div>
      <div>MAIN</div>
      <div>MAIN</div>
      <div>MAIN</div>
      <div>MAIN</div>
      <div>MAIN</div>
      <div>MAIN</div>
      <div>MAIN</div>
      <div>MAIN</div>
      <div>MAIN</div>
      <div>MAIN</div>
      <div>MAIN</div>
      <div>MAIN</div>
      <div>MAIN</div>
      <div>MAIN</div>
      <div>MAIN</div>
      <div>MAIN</div>
      <div>MAIN</div>
      <div>MAIN</div>
    </>
  );
}
